<!-- Place this tag where you want the button to render. -->
<a class="github-button" href="https://github.com/PinkBroccoli/PinkBroccoli.github.io" data-color-scheme="no-preference: light; light: light; dark: dark;" data-icon="octicon-star" aria-label="Star PinkBroccoli/PinkBroccoli.github.io on GitHub">Star</a>
