
<!-- Place this tag where you want the button to render. -->
<a class="github-button" href="https://github.com/ntkme/github-buttons/packages" data-icon="octicon-package" aria-label="Install this package ntkme/github-buttons on GitHub">Install this package</a>
